### ISSUE TITLE
一个场外话题：如何能够更换中文显示的字体样式？

### ISSUE THREAD

**Issue by KNQMuzzi** [chinese-liliths-throne/liliths-throne-chinese-localization#2]
如题，如何能够更换中文显示的字体样式？
宋体看着有点累😂

**Comment by SHTU-YuxuanGe** [comment]
汉化版游戏应该有自带字体，而非宋体，尝试安装思源黑体或重新下载试试

**Comment by CKRainbow** [comment]
游戏有自带思源黑体，可以尝试安装思源黑体或重新下载游戏

**Comment by KNQMuzzi** [comment]
以上两种都尝试了，这是我目前的游戏界面截图，中文部分仍是类似于宋体的样式
![PixPin_2024-05-09_11-29-01](https://github.com/chinese-liliths-throne/liliths-throne-chinese-localization/assets/49626345/0d8519d8-b065-43ca-b9b7-8647e3fa79d2)

**Comment by KNQMuzzi** [comment]
目前更换一个新的目录安装之后问题解决了，很奇怪

**Comment by KNQMuzzi** [comment]
当目录路径存在 `#` 的时候，中文字符会失效
