### ISSUE TITLE
macos系统双击游戏运行，弹窗显示java意外退出，请问如何操作？

### ISSUE THREAD

**Issue by Ray26130001** [chinese-liliths-throne/liliths-throne-chinese-localization#3]
您好，针对问题我进行了以下尝试：
1.检查java配置环境变量无误；
2.删除java并重新安装；
3.确认下载的压缩包版本无误；
4.重启计算机。

以上尝试均未成功，弹窗显示java意外退出，Termination Reason: Namespace SIGNAL, Code 6 Abort trap: 6

请问问题是出在哪一环？如何解决？谢谢解答。

**Comment by CKRainbow** [comment]
抱歉由于某些原因需要删除该issue，如果您在邮件中看到相关内容，可以尝试再次提出issue
