### ISSUE TITLE
为Windows构建Arm64

### ISSUE THREAD

**Issue by Elaman0117** [chinese-liliths-throne/liliths-throne-chinese-localization#4]

**Comment by CKRainbow** [comment]
Maven似乎没有构建好的win arm64 javafx

**Comment by Elaman0117** [comment]
> Maven似乎没有构建好的win arm64 javafx

找到https://bell-sw.com/pages/downloads/#jdk-21-lts 下有Windows Arm64的JDK，而且我看有人在https://www.reddit.com/r/JavaFX/comments/14mjegl/is_there_a_build_of_javafx_17_for_arm64_windows/ 里说它也带JavaFX，不过我确实不太懂Java。

**Comment by CKRainbow** [comment]
莉莉丝代码的适配性其实不太好，现在javafx用的是18.0.2，我也试过更换其他版本，都会出现一些问题。所以很难说自带的javafx能否使用。我或许会试一下，不过很可能没法成功。
